"""Torch-free audio front-end: conventions, log-mel, pause detection, augmentation."""

from eot.audio.augment import add_room_tone, noise_floor_dbfs, tail_texture, telephony_augment
from eot.audio.frontend import (
    GRID_STEP,
    N_FRAMES,
    N_MELS,
    SAMPLE_RATE,
    SCORE_POINT,
    WINDOW_SECONDS,
    causal_prefix,
    decode_payload,
    last_window,
    load_audio_bytes,
    load_wav,
    log_mel,
    resample,
    resample_antialiased,
    to_16k,
    to_float32,
    to_mono,
    to_pcm16_bytes,
)
from eot.audio.pauses import (
    SILERO_VAD_SHA256,
    SILERO_VAD_VERSION,
    PauseDetector,
    PauseSpan,
    SileroVAD,
    Span,
    digital_silence_fraction,
    ensemble_pauses,
    estimate_snr_db,
    frame_db,
    silence_spans,
    silence_spans_adaptive,
    vad_quiet_mask,
)

# Only names used outside ``eot.audio`` are re-exported; detector internals live in ``eot.audio.pauses``.
__all__ = [
    "GRID_STEP",
    "N_FRAMES",
    "N_MELS",
    "SAMPLE_RATE",
    "SCORE_POINT",
    "SILERO_VAD_SHA256",
    "SILERO_VAD_VERSION",
    "WINDOW_SECONDS",
    "PauseDetector",
    "PauseSpan",
    "SileroVAD",
    "Span",
    "add_room_tone",
    "causal_prefix",
    "decode_payload",
    "digital_silence_fraction",
    "ensemble_pauses",
    "estimate_snr_db",
    "frame_db",
    "last_window",
    "load_audio_bytes",
    "load_wav",
    "log_mel",
    "noise_floor_dbfs",
    "resample",
    "resample_antialiased",
    "silence_spans",
    "silence_spans_adaptive",
    "tail_texture",
    "telephony_augment",
    "to_16k",
    "to_float32",
    "to_mono",
    "to_pcm16_bytes",
    "vad_quiet_mask",
]
